// Code generated by protoc-gen-go. DO NOT EDIT.
// source: findmaxpb/findmax.proto

package findmaxpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindMaxRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxRequest) Reset()         { *m = FindMaxRequest{} }
func (m *FindMaxRequest) String() string { return proto.CompactTextString(m) }
func (*FindMaxRequest) ProtoMessage()    {}
func (*FindMaxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5349661f99d8a73, []int{0}
}

func (m *FindMaxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxRequest.Unmarshal(m, b)
}
func (m *FindMaxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxRequest.Marshal(b, m, deterministic)
}
func (m *FindMaxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxRequest.Merge(m, src)
}
func (m *FindMaxRequest) XXX_Size() int {
	return xxx_messageInfo_FindMaxRequest.Size(m)
}
func (m *FindMaxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxRequest proto.InternalMessageInfo

func (m *FindMaxRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type FindMaxResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindMaxResponse) Reset()         { *m = FindMaxResponse{} }
func (m *FindMaxResponse) String() string { return proto.CompactTextString(m) }
func (*FindMaxResponse) ProtoMessage()    {}
func (*FindMaxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5349661f99d8a73, []int{1}
}

func (m *FindMaxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindMaxResponse.Unmarshal(m, b)
}
func (m *FindMaxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindMaxResponse.Marshal(b, m, deterministic)
}
func (m *FindMaxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindMaxResponse.Merge(m, src)
}
func (m *FindMaxResponse) XXX_Size() int {
	return xxx_messageInfo_FindMaxResponse.Size(m)
}
func (m *FindMaxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindMaxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindMaxResponse proto.InternalMessageInfo

func (m *FindMaxResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*FindMaxRequest)(nil), "findmax.FindMaxRequest")
	proto.RegisterType((*FindMaxResponse)(nil), "findmax.FindMaxResponse")
}

func init() {
	proto.RegisterFile("findmaxpb/findmax.proto", fileDescriptor_a5349661f99d8a73)
}

var fileDescriptor_a5349661f99d8a73 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xcb, 0xcc, 0x4b,
	0xc9, 0x4d, 0xac, 0x28, 0x48, 0xd2, 0x87, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8,
	0xa1, 0x5c, 0x25, 0x39, 0x2e, 0x3e, 0xb7, 0xcc, 0xbc, 0x14, 0xdf, 0xc4, 0x8a, 0xa0, 0xd4, 0xc2,
	0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x1e, 0x2e, 0xc6, 0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20,
	0xc6, 0x3c, 0x25, 0x4d, 0x2e, 0x7e, 0xb8, 0x7c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x18,
	0x17, 0x5b, 0x51, 0x6a, 0x71, 0x69, 0x4e, 0x09, 0x54, 0x15, 0x94, 0x67, 0x14, 0x02, 0x37, 0x2a,
	0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x89, 0x8b, 0x1d, 0x2a, 0x22, 0x24, 0xae, 0x07,
	0x73, 0x00, 0xaa, 0x75, 0x52, 0x12, 0x98, 0x12, 0x10, 0x7b, 0x94, 0x18, 0x34, 0x18, 0x0d, 0x18,
	0x9d, 0xb8, 0xa3, 0x38, 0xe1, 0x9e, 0x48, 0x62, 0x03, 0xbb, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0xe9, 0x55, 0x7a, 0xd8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FindMaxServiceClient is the client API for FindMaxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FindMaxServiceClient interface {
	// client streaming
	FindMax(ctx context.Context, opts ...grpc.CallOption) (FindMaxService_FindMaxClient, error)
}

type findMaxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFindMaxServiceClient(cc grpc.ClientConnInterface) FindMaxServiceClient {
	return &findMaxServiceClient{cc}
}

func (c *findMaxServiceClient) FindMax(ctx context.Context, opts ...grpc.CallOption) (FindMaxService_FindMaxClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FindMaxService_serviceDesc.Streams[0], "/findmax.FindMaxService/FindMax", opts...)
	if err != nil {
		return nil, err
	}
	x := &findMaxServiceFindMaxClient{stream}
	return x, nil
}

type FindMaxService_FindMaxClient interface {
	Send(*FindMaxRequest) error
	Recv() (*FindMaxResponse, error)
	grpc.ClientStream
}

type findMaxServiceFindMaxClient struct {
	grpc.ClientStream
}

func (x *findMaxServiceFindMaxClient) Send(m *FindMaxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *findMaxServiceFindMaxClient) Recv() (*FindMaxResponse, error) {
	m := new(FindMaxResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FindMaxServiceServer is the server API for FindMaxService service.
type FindMaxServiceServer interface {
	// client streaming
	FindMax(FindMaxService_FindMaxServer) error
}

// UnimplementedFindMaxServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFindMaxServiceServer struct {
}

func (*UnimplementedFindMaxServiceServer) FindMax(srv FindMaxService_FindMaxServer) error {
	return status.Errorf(codes.Unimplemented, "method FindMax not implemented")
}

func RegisterFindMaxServiceServer(s *grpc.Server, srv FindMaxServiceServer) {
	s.RegisterService(&_FindMaxService_serviceDesc, srv)
}

func _FindMaxService_FindMax_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FindMaxServiceServer).FindMax(&findMaxServiceFindMaxServer{stream})
}

type FindMaxService_FindMaxServer interface {
	Send(*FindMaxResponse) error
	Recv() (*FindMaxRequest, error)
	grpc.ServerStream
}

type findMaxServiceFindMaxServer struct {
	grpc.ServerStream
}

func (x *findMaxServiceFindMaxServer) Send(m *FindMaxResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *findMaxServiceFindMaxServer) Recv() (*FindMaxRequest, error) {
	m := new(FindMaxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FindMaxService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "findmax.FindMaxService",
	HandlerType: (*FindMaxServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindMax",
			Handler:       _FindMaxService_FindMax_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "findmaxpb/findmax.proto",
}
