// Code generated by protoc-gen-go. DO NOT EDIT.
// source: primenumberpb/primenumber.proto

package primenumberpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PrimeNumberRequest struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberRequest) Reset()         { *m = PrimeNumberRequest{} }
func (m *PrimeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberRequest) ProtoMessage()    {}
func (*PrimeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33eebd64a020450b, []int{0}
}

func (m *PrimeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberRequest.Unmarshal(m, b)
}
func (m *PrimeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberRequest.Marshal(b, m, deterministic)
}
func (m *PrimeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberRequest.Merge(m, src)
}
func (m *PrimeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberRequest.Size(m)
}
func (m *PrimeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberRequest proto.InternalMessageInfo

func (m *PrimeNumberRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type PrimeNumberResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeNumberResponse) Reset()         { *m = PrimeNumberResponse{} }
func (m *PrimeNumberResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberResponse) ProtoMessage()    {}
func (*PrimeNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33eebd64a020450b, []int{1}
}

func (m *PrimeNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeNumberResponse.Unmarshal(m, b)
}
func (m *PrimeNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeNumberResponse.Marshal(b, m, deterministic)
}
func (m *PrimeNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeNumberResponse.Merge(m, src)
}
func (m *PrimeNumberResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeNumberResponse.Size(m)
}
func (m *PrimeNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeNumberResponse proto.InternalMessageInfo

func (m *PrimeNumberResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PrimeNumberRequest)(nil), "primenumber.PrimeNumberRequest")
	proto.RegisterType((*PrimeNumberResponse)(nil), "primenumber.PrimeNumberResponse")
}

func init() {
	proto.RegisterFile("primenumberpb/primenumber.proto", fileDescriptor_33eebd64a020450b)
}

var fileDescriptor_33eebd64a020450b = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0xcc,
	0x4d, 0xcd, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d, 0x2a, 0x48, 0xd2, 0x47, 0xe2, 0xe9, 0x15, 0x14, 0xe5,
	0x97, 0xe4, 0x0b, 0x71, 0x23, 0x09, 0x29, 0xa9, 0x71, 0x09, 0x05, 0x80, 0xb8, 0x7e, 0x60, 0x6e,
	0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x5e, 0x69, 0xae, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x6b, 0x10, 0x88, 0xa9, 0xa4, 0xcb, 0x25, 0x8c, 0xa2, 0xae, 0xb8, 0x20, 0x3f,
	0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0xaa, 0x16, 0xca,
	0x33, 0x2a, 0x47, 0x31, 0x36, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x28, 0x91, 0x4b, 0x02,
	0x49, 0xd4, 0x25, 0x35, 0x39, 0x3f, 0xb7, 0x20, 0xbf, 0x38, 0xb3, 0x24, 0x33, 0x3f, 0x4f, 0x48,
	0x5e, 0x0f, 0xd9, 0xa5, 0x98, 0x6e, 0x92, 0x52, 0xc0, 0xad, 0x00, 0xe2, 0x18, 0x25, 0x06, 0x03,
	0x46, 0x27, 0xfe, 0x28, 0x5e, 0x14, 0xff, 0x27, 0xb1, 0x81, 0x3d, 0x6d, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x00, 0x9b, 0xe8, 0x4a, 0x17, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeNumberServiceClient is the client API for PrimeNumberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeNumberServiceClient interface {
	// server streaming
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeNumberDecompositionClient, error)
}

type primeNumberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeNumberServiceClient(cc grpc.ClientConnInterface) PrimeNumberServiceClient {
	return &primeNumberServiceClient{cc}
}

func (c *primeNumberServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberRequest, opts ...grpc.CallOption) (PrimeNumberService_PrimeNumberDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeNumberService_serviceDesc.Streams[0], "/primenumber.PrimeNumberService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeNumberServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeNumberService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberResponse, error)
	grpc.ClientStream
}

type primeNumberServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *primeNumberServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberResponse, error) {
	m := new(PrimeNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeNumberServiceServer is the server API for PrimeNumberService service.
type PrimeNumberServiceServer interface {
	// server streaming
	PrimeNumberDecomposition(*PrimeNumberRequest, PrimeNumberService_PrimeNumberDecompositionServer) error
}

// UnimplementedPrimeNumberServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeNumberServiceServer struct {
}

func (*UnimplementedPrimeNumberServiceServer) PrimeNumberDecomposition(req *PrimeNumberRequest, srv PrimeNumberService_PrimeNumberDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomposition not implemented")
}

func RegisterPrimeNumberServiceServer(s *grpc.Server, srv PrimeNumberServiceServer) {
	s.RegisterService(&_PrimeNumberService_serviceDesc, srv)
}

func _PrimeNumberService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeNumberServiceServer).PrimeNumberDecomposition(m, &primeNumberServicePrimeNumberDecompositionServer{stream})
}

type PrimeNumberService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberResponse) error
	grpc.ServerStream
}

type primeNumberServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *primeNumberServicePrimeNumberDecompositionServer) Send(m *PrimeNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeNumberService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primenumber.PrimeNumberService",
	HandlerType: (*PrimeNumberServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _PrimeNumberService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "primenumberpb/primenumber.proto",
}
